version: '3.9'

services:
  redis:
    restart: "no"
    image: "redis:alpine"
    hostname: redis
    container_name: rediska
    ports:
      - '6379:6379'

  backend:
    restart: "no"
    build:
      dockerfile: Dockerfile
    command: sh -c "gunicorn MySite.wsgi --bind 0.0.0.0:8000 -w 4"
    container_name: project1
    image: backend_image
    ports:
      - '8000:8000'
    links:
      - redis
    depends_on:
      - redis

  celery:
    build: ./
    command: celery -A MySite worker -l INFO
    container_name: celerys
    environment:
      - CELERY_BROKER=redis://redis:6379/0
      - CELERY_BACKEND=redis://redis:6379/0
    depends_on:
      - redis