# Generated by Django 4.0.3 on 2022-04-14 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_alter_post_options_alter_post_is_published_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='photo',
        ),
    ]
