# Generated by Django 4.0.3 on 2022-04-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_userpost'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userpost',
            options={'ordering': ['time_create', 'title'], 'verbose_name': 'Пост пользователя', 'verbose_name_plural': 'Посты пользователей'},
        ),
        migrations.AddField(
            model_name='userpost',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
